### ISSUE TITLE
Is this expected to work macOS with darwin-nix?

### ISSUE THREAD

**Issue by stuartforrest-infinity** [msteen/nixos-vsliveshare#10]
I've had a go at getting it running but with no real success. The most meaningful error is: `The option `services.gnome3' does not exist`. This makes me thing it is not intended for macOS.

**Comment by msteen** [comment]
Thank you for reporting this. I remember seeing that error when upgrading to the latest stable Nixpkgs, it is now called `services.gnome` (the version is dropped), so I should update the module file to reflect this. Running this project on a NixOS system and using a macOS client should work fine. If you are somehow running it under `darwin-nix`, then I got no clue, as I don't any machines that run it. Also, it seems I have yet to update the README, as this project is now replaced by installing:
`(vscode-with-extensions.override { vscodeExtensions = with vscode-extensions; [ ms-vsliveshare.vsliveshare ]; })`
