### ISSUE TITLE
Installing the Live Share extensions breaks the script

### ISSUE THREAD

**Issue by terlar** [msteen/nixos-vsliveshare#6]
Since the script is using `ms-vsliveshare.vsliveshare-*` it matches various Live Share extensions such as audio and pack. See:
```
$ find ~/.vscode/extensions -name 'ms-vsliveshare.vsliveshare-*'
/home/user/.vscode/extensions/ms-vsliveshare.vsliveshare-audio-0.1.80
/home/user/.vscode/extensions/ms-vsliveshare.vsliveshare-pack-0.3.4
/home/user/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.1783
```
If you have this directory structure the `fix-vsliveshare` won't work, since it will match one of the other extensions.
```
$ fix-vsliveshare
Invalid version 'pack-0.3.4'.
```

If I remove those other extensions, it will work again.

**Comment by msteen** [comment]
Thank you for making me aware of this! I will try to make the selector more strict.
